import{a as h,S as C,i as l}from"./assets/vendor-CRwkH7JT.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const p=({webformatURL:s,largeImageURL:e,tags:o,likes:a,views:t,comments:r,downloads:n})=>`<li class="gallery-item">
        <a href="${e}">
          <img src="${s}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p>Likes: ${a}</p>
          <p>Views: ${t}</p>
          <p>Comments: ${r}</p>
          <p>Downloads: ${n}</p>
        </div>
      </li>`;h.defaults.baseURL="https://pixabay.com";const y=(s,e)=>{const o={params:{key:"45636659-15209a2e9fad59db9d3b17888",q:s,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return h.get("/api/",o)},g=document.querySelector(".search-form"),d=document.querySelector(".gallery-list"),u=document.querySelector(".loader"),i=document.querySelector(".load-btn");let c=1,f="",m=0,L=0;const b=new C(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250}),v=async s=>{try{if(s.preventDefault(),f=g.elements.user_query.value.trim(),f===""){l.show({message:"Please enter a search term.",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),d.innerHTML="",i.classList.add("is-hidden");return}c=1;const e=await y(f,c);if(g.reset(),d.innerHTML="",e.data.hits.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),i.classList.add("is-hidden");return}const o=e.data.hits.map(t=>p(t)).join("");d.innerHTML=o,b.refresh(),L=document.querySelector(".gallery-item").getBoundingClientRect().height,m=Math.ceil(e.data.totalHits/e.data.hits.length),m>1?i.classList.remove("is-hidden"):i.classList.add("is-hidden")}catch(e){l.error({message:`Something went wrong: ${e.message}`,backgroundColor:"#ef4040",messageColor:"#ffffff",position:"topRight"})}},w=async s=>{try{u.classList.remove("is-hidden"),c++;const e=await y(f,c);console.log(e);const o=e.data.hits.map(a=>p(a)).join("");if(d.insertAdjacentHTML("beforeend",o),b.refresh(),scrollBy({top:L*2,behavior:"smooth"}),c>=m){l.warning({message:"We're sorry, but you've reached the end of search results",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),i.classList.add("is-hidden");return}}catch(e){l.error({message:`Something went wrong: ${e.message}`,backgroundColor:"#ef4040",messageColor:"#ffffff",position:"topRight"})}finally{u.classList.add("is-hidden")}};g.addEventListener("submit",v);i.addEventListener("click",w);
//# sourceMappingURL=index.js.map
