import{a as y,S as C,A as S,b as q,N as A,K as P,i as l}from"./assets/vendor-Bkjd0PGO.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const b=({webformatURL:s,largeImageURL:e,tags:o,likes:a,views:t,comments:r,downloads:i})=>`<li class="gallery-item">
        <a href="${e}">
          <img src="${s}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p>Likes: ${a}</p>
          <p>Views: ${t}</p>
          <p>Comments: ${r}</p>
          <p>Downloads: ${i}</p>
        </div>
      </li>`;y.defaults.baseURL="https://pixabay.com";const L=(s,e)=>{const o={params:{key:"45636659-15209a2e9fad59db9d3b17888",q:s,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return y.get("/api/",o)},g=document.querySelector(".search-form"),d=document.querySelector(".gallery-list"),h=document.querySelector(".loader"),n=document.querySelector(".load-btn");let c=1,u="",m=0,v=0;const w=new C(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250}),E=async s=>{try{if(s.preventDefault(),u=g.elements.user_query.value.trim(),u===""){l.show({message:"Please enter a search term.",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),d.innerHTML="",n.classList.add("is-hidden");return}c=1;const e=await L(u,c);if(g.reset(),d.innerHTML="",e.data.hits.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),n.classList.add("is-hidden");return}const o=e.data.hits.map(t=>b(t)).join("");d.innerHTML=o,w.refresh(),v=document.querySelector(".gallery-item").getBoundingClientRect().height,m=Math.ceil(e.data.totalHits/e.data.hits.length),m>1?n.classList.remove("is-hidden"):n.classList.add("is-hidden")}catch(e){l.error({message:`Something went wrong: ${e.message}`,backgroundColor:"#ef4040",messageColor:"#ffffff",position:"topRight"})}},M=async s=>{try{h.classList.remove("is-hidden"),c++;const e=await L(u,c);console.log(e);const o=e.data.hits.map(a=>b(a)).join("");if(d.insertAdjacentHTML("beforeend",o),w.refresh(),scrollBy({top:v*2,behavior:"smooth"}),c>=m){l.warning({message:"We're sorry, but you've reached the end of search results",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),n.classList.add("is-hidden");return}}catch(e){l.error({message:`Something went wrong: ${e.message}`,backgroundColor:"#ef4040",messageColor:"#ffffff",position:"topRight"})}finally{h.classList.add("is-hidden")}};g.addEventListener("submit",E);n.addEventListener("click",M);new S(".about-me-list",{duration:300,showMultiple:!1,openOnInit:[0]});new q(".swiper-container-about",{modules:[A,P],loop:!0,slidesPerView:2,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:6}},navigation:{nextEl:".swiper-button-next"},keyboard:{enabled:!0,onlyInViewport:!0},touchEventsTarget:"container",allowSlidePrev:!1});document.querySelector(".section-about");document.addEventListener("DOMContentLoaded",function(){document.querySelector(".about-picture");const s=document.querySelectorAll("source"),e=document.querySelector(".about-photo");new IntersectionObserver((a,t)=>{a.forEach(r=>{if(r.isIntersecting){s.forEach(f=>{const p=f.getAttribute("data-srcset");p&&(f.removeAttribute("data-srcset"),f.setAttribute("srcset",p))});const i=e.getAttribute("data-src");i&&(e.removeAttribute("data-src"),e.setAttribute("src",i)),t.unobserve(e)}})}).observe(e)});
//# sourceMappingURL=index.js.map
