import{a as b,S,A as q,b as A,N as P,K as E,i as c}from"./assets/vendor-Bkjd0PGO.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const L=({webformatURL:s,largeImageURL:e,tags:o,likes:a,views:t,comments:r,downloads:i})=>`<li class="gallery-item">
        <a href="${e}">
          <img src="${s}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p>Likes: ${a}</p>
          <p>Views: ${t}</p>
          <p>Comments: ${r}</p>
          <p>Downloads: ${i}</p>
        </div>
      </li>`;b.defaults.baseURL="https://pixabay.com";const v=(s,e)=>{const o={params:{key:"45636659-15209a2e9fad59db9d3b17888",q:s,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return b.get("/api/",o)},g=document.querySelector(".search-form"),d=document.querySelector(".gallery-list"),y=document.querySelector(".loader"),n=document.querySelector(".load-btn");let l=1,u="",m=0,w=0;const C=new S(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250}),M=async s=>{try{if(s.preventDefault(),u=g.elements.user_query.value.trim(),u===""){c.show({message:"Please enter a search term.",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),d.innerHTML="",n.classList.add("is-hidden");return}l=1;const e=await v(u,l);if(g.reset(),d.innerHTML="",e.data.hits.length===0){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),n.classList.add("is-hidden");return}const o=e.data.hits.map(t=>L(t)).join("");d.innerHTML=o,C.refresh(),w=document.querySelector(".gallery-item").getBoundingClientRect().height,m=Math.ceil(e.data.totalHits/e.data.hits.length),m>1?n.classList.remove("is-hidden"):n.classList.add("is-hidden")}catch(e){c.error({message:`Something went wrong: ${e.message}`,backgroundColor:"#ef4040",messageColor:"#ffffff",position:"topRight"})}},O=async s=>{try{y.classList.remove("is-hidden"),l++;const e=await v(u,l);console.log(e);const o=e.data.hits.map(a=>L(a)).join("");if(d.insertAdjacentHTML("beforeend",o),C.refresh(),scrollBy({top:w*2,behavior:"smooth"}),l>=m){c.warning({message:"We're sorry, but you've reached the end of search results",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight"}),n.classList.add("is-hidden");return}}catch(e){c.error({message:`Something went wrong: ${e.message}`,backgroundColor:"#ef4040",messageColor:"#ffffff",position:"topRight"})}finally{y.classList.add("is-hidden")}};g.addEventListener("submit",M);n.addEventListener("click",O);new q(".about-me-list",{duration:300,showMultiple:!1,openOnInit:[0]});new A(".swiper-container-about",{modules:[P,E],loop:!0,slidesPerView:2,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:6}},navigation:{nextEl:".swiper-button-next"},keyboard:{enabled:!0,onlyInViewport:!0},touchEventsTarget:"container",allowSlidePrev:!1});document.querySelector(".section-about");document.addEventListener("DOMContentLoaded",function(){const s=document.querySelector(".about-picture"),e=document.querySelectorAll("source"),o=document.querySelector(".about-photo"),a=new IntersectionObserver((t,r)=>{t.forEach(i=>{if(i.isIntersecting){e.forEach(f=>{const h=f.getAttribute("data-srcset");h&&(f.removeAttribute("data-srcset"),f.setAttribute("srcset",h))});const p=o.getAttribute("data-src");p&&(o.removeAttribute("data-src"),o.setAttribute("src",p)),r.unobserve(s),r.unobserve(o)}})});a.observe(s),a.observe(o)});
//# sourceMappingURL=index.js.map
